### PR TITLE
add option for celsius

### PR DESCRIPTION
**Pull request by PowerSnail**
For #15.

### CODE REVIEW

**Comment by danerwilliams** [comment]
So a couple things on this:
* Could we avoid setting an environment variable to represent the unit of temperature
* Instead of changing the regex filter based on the specified unit of temperature, maybe converting from F to C with a conversion formula would be simpler?

**Comment by PowerSnail** [comment]
I've changed it to use cli argument instead of environment variable.

Regarding the second point, may I ask why? Since the `curl`ed result already contains `deg;C`, what's wrong with `grep`-ing it?

**Comment by danerwilliams** [comment]
So I wouldn't say there is anything wrong with this approach and it seems to work fine. There are just two reasons why I think another approach would be better:
* I plan on scraping a different site to add international support for weather as mentioned in #16 
    - If we just made a simple conversion function to celsius then this code would be more reusable
* By setting an option with "f" or "c" I feel like there is more room for error by the user by passing in a wrong input to that option
    - If we just make it something like weather-celsius false (or true) then everything remains pretty much fool proof (I know this is nitpicking to an extent)

**Comment by danerwilliams** [comment]
#21

**Pull request closed without merging**
