### PR TITLE
 Issue #67 Add git functionality

### PR DESCRIPTION
**Pull request by joeperri95**
## Issue
Issue #67 Git status module

## Description of Changes

This commit will add to the status bar with the git branch of the current repo. If there are outstanding changes the text color is set to red. 

## Testing

cd into a directory not containing a git repo -> there should be no text just a small empty box 
cd into a directory containing a git repo -> text should be the currently checked out branch 
cd into a directory containing a git repo that is up to date -> text should be dark gray
cd into a directory containing a git repo that is not up to date -> text should be red

### CODE REVIEW

**Comment by ethancedwards8** [comment]
Oh man this is great work! Thank you for submitting this! One thing though, sometimes the status is cut off:

2021-06-20-143305_194x64_scrot

**Comment by joeperri95** [comment]
Sorry I tried most of the option combinations and could not reproduce that issue. Can you give me some of your environment info?

**Comment by ethancedwards8** [comment]
```
# enable mouse mode
set-option -g mouse on
set -g @dracula-border-contrast true
set -g @dracula-show-network false
# set -g @dracula-show-battery true
set -g @dracula-military-time true
set -g @dracula-show-weather false
set -g @dracula-show-powerline false
set -g @dracula-show-left-icon session
set -g @dracula-cpu-usage true
set -g @dracula-ram-usage true
set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
# set -g @dracula-show-time true
set -g @dracula-refresh-rate 5
```

**Comment by ethancedwards8** [comment]
@joeperri95 It seems this issue was on my end, bad terminal configuration. Its working as expected now, please fix merge conflicts and conform to the new standards and I'll be happy to merge this in for you!

**Comment by joeperri95** [comment]
Hey I updated what I had to work with the new plugin system (which is great btw). The new system unfortunately means that the text can't easily be recolored on the fly. Instead I opted to use a different user configurable symbol to indicate whether the branch is up to date or has diverged from HEAD. Also new is a brief summary that shows the number of files that have been modified, added, etc.

**Comment by ethancedwards8** [comment]
Amazing work, thanks!

**Pull request merged**
