### PR TITLE
Add load average support

### PR DESCRIPTION
**Pull request by adrianmihalko**
This PR adds support for load average to CPU info script.

Screenshot 2021-12-22 at 23 15 23

Also resolves request #118

### CODE REVIEW

**Comment by ethancedwards8** [comment]
How does one interpret those numbers?

**Comment by adrianmihalko** [comment]
It's a quick overview of your last 1-5-15 min CPU load.

https://en.wikipedia.org/wiki/Load_(computing)

**Comment by ethancedwards8** [comment]
I see, add an explanation to the docs file and I'll merge it, thanks for contributing!

**Comment by ABitMoreDepth** [comment]
This looks great, thanks!

**Pull request merged**
