### PR TITLE
Added RAM Percentage per issue #36

### PR DESCRIPTION
**Pull request by ethancedwards8**
Working cleanly on Linux powerline and non powerline

### CODE REVIEW

**Comment by ethancedwards8** [comment]
#36

**Comment by danerwilliams** [comment]
So now that we have a lot more information to potentially be displayed in the status bar I think we need to consider what colors we should be using or determining a way for the colors and / or the order of the different modules are displayed on the status bar. What is everyone's thoughts? It just looks kind of weird to me when we have two orange modules and when this is merged two cyan modules.

**Comment by ethancedwards8** [comment]
I agree, I didn't know what colors to choose, I was just trying to get the functionality, since you're the owner I was thinking you could just pick the colors.

**Comment by ethancedwards8** [comment]
I was thinking about a way to choose what order the modules go in, maybe using an array, and you can specify the order in the array, within the .tmux.conf file

**Comment by ethancedwards8** [comment]
I was also thinking about combining the RAM and CPU modules, and if both are enabled in the .tmux.conf file then it could be in one segment in the bar, but if only one is enabled then its still a singular segment, so if both were enabled it would be the same color, and closer together, if that makes any sense

**Comment by danerwilliams** [comment]
Yeah I definitely think we need to make it more configurable somehow. Having a list in the configuration like you mentioned could be a good idea. I'll merge for now to give the functionality and then raise an issue for making it more configurable.

**Comment by danerwilliams** [comment]
Before I merge are you able to add mac compatibility?

**Comment by ethancedwards8** [comment]
I do have a command I think will work, but I can't test it currently

**Comment by ethancedwards8** [comment]
`ps -A -o %mem | awk '{mem += $2} END {print mem}'`

**Comment by ethancedwards8** [comment]
I think that will work, if you could test it and give me the output that'd be great

**Comment by ethancedwards8** [comment]
Man, I really need to get a Mac lol, I borrow my moms whenever I need to test code.

**Comment by ethancedwards8** [comment]
Also another interesting question, should we add support for the *BSD's?

**Comment by ciehanski** [comment]
@ethancedwards8 looks like `ps -A -o %mem | awk '{mem += $1} END {print mem}'` works for me on my mac, but just to specify, it only polls _app_ memory and not _wired_ memory as well.

**Comment by ethancedwards8** [comment]
Okay, forgive the stupid question but, what’s the difference between app memory and wired memory? I could probably achieve the total_used/total_mem, but the reason I chose the percentage is because the CPU is percentage based.

**Comment by danerwilliams** [comment]
So what I’m reading is that the total memory used is the sum of wired memory, app memory, and compressed memory. Maybe there is a way to get memory used with out needing to individually gather all 3 of those figures?

**Comment by danerwilliams** [comment]
And if you would like support for BSD, then please open an issue.

**Comment by ethancedwards8** [comment]
I think we should just support what we're doing right now, and if someone comes along and wants BSD support I think we could do it. But for the memory issue, I'm not sure, if you run the `free -m` or `free -h` command what does it output?

**Comment by ethancedwards8** [comment]
Actually, I think that's a Linux only command, I'll search through stackoverflow and see if I can find something.

**Comment by ciehanski** [comment]
Look into:
```bash
❯ top -l 1 -s 0 | grep PhysMem
PhysMem: 14G used (3148M wired), 2503M unused.
```
You could probably grep the output and get the actual results.

**Comment by ethancedwards8** [comment]
Interesting.. thanks for finding that, did you find this off of anything? Or did you come up with this, if you found it, can you link the source please? I feel this could be what we are looking for, sadly it doesn't run on Linux, so it'll be hard for me to test, so I'll be in touch.

**Comment by ciehanski** [comment]
I found it [here](https://apple.stackexchange.com/a/46655), good ol' stackx. I'll play around with the command and try to get something that works, but I am willing to help test any command you come up with. I am going with what the Activity Monitor reports which is `Memory Used` as `PhysMem(used) - wired(used)`.

Final output in dracula should look like (IMO):
 ```bash
10G/16G
```

**Comment by ethancedwards8** [comment]
Okay, well I'm on vacation, so I probably won't be able to get out a solution for about a week. So, if @danerwilliams wants to merge my current PR, or leave out a commit or whatever he wants to do, you can take over and do the Mac support, and I can try and help out when my vacation is over.

**Comment by ethancedwards8** [comment]
Does this work? I had some free time and decided to work on this, if this works tell me the output, if it doesn't, back to the drawing board I guess.

**Comment by ethancedwards8** [comment]
[How it looks](https://drive.google.com/file/d/1GaoV1LeoP_62JHDl8qyxlQ5A6_m2XD4E/view)

**Comment by ethancedwards8** [comment]
Okay, sorry for all of the excess commits, I was testing on my moms old mac, and I was pushing and editing the code from my desktop.

**Comment by ethancedwards8** [comment]
Everything is working, I renamed the variables from 'dracula-***-percentage' to 'dracula-***-usage', because for the RAM it shows the usage/total per @ciehanski request, thats not the percentage thats the usage.

**Comment by ethancedwards8** [comment]
Sooo any feedback?

**Comment by danerwilliams** [comment]
Just tested and it seems like RAM on mac isn't accurate. it's saying 13G/16GB when htop is showing 7 gb usage. Also, why just G for the used and GB for available?

**Comment by ethancedwards8** [comment]
The G instead of GB was unintentional, I didn't see it.

**Comment by ethancedwards8** [comment]
I've been parsing ram out from top, and it wasn't the same as htop, I've yet to find a command that gives me the same output to htop. I also tried vm_stat

**Comment by danerwilliams** [comment]
hmmm, it's weird to me that all of these different programs would be getting different readings

**Comment by danerwilliams** [comment]
From this it sounds like you maybe could get the same number as htop with the data provided in top if you do some calculations:
https://askubuntu.com/questions/791270/why-are-memory-statistics-in-top-and-htop-different

**Comment by ethancedwards8** [comment]
Okay, I'll look into that, thanks.

**Comment by ethancedwards8** [comment]
Okay, I had some spare time today and was working on a solution. I should have a working commit tomorrow or the day after that.

**Comment by ethancedwards8** [comment]
Everything is good now, if it is higher than htop the reason behind that is it rounds up.

**Pull request merged**
