### PR TITLE
Customizations

### PR DESCRIPTION
**Pull request by o0th**
**Changes**

- Plugin order and customization #42 
- Custom label for cpu_info, gpu_usage and ram_info
- Normalize gpu_usage len
- Fix indentation in files
- Fix bug in ram usage #106

**Config**
```conf
set -g @dracula-plugins "cpu-usage gpu-usage ram-usage"

set -g @dracula-ram-usage-label ﬙
set -g @dracula-ram-usage-colors "dark_gray white"

set -g @dracula-gpu-usage-label 
set -g @dracula-gpu-usage-colors "dark_gray white"

set -g @dracula-cpu-usage-label 
set -g @dracula-cpu-usage-colors "dark_gray white"
```

**Normal**
tmux-normal

**Powerline**
tmux-powershell

### CODE REVIEW

**Comment by ethancedwards8** [comment]
This is great work! One thing I do ask is can you separate the formatting stuff into a separate commit? I know thats a lot to ask for, but it'll make things easier to look into if something is broken.

**Comment by ethancedwards8** [comment]
Also, I'm going to need some INSTALL.md documentation.

**Comment by o0th** [comment]
No problem at all. About the formatting, is it the `.editorconfig` OK or do you prefer a different format?

**Comment by ethancedwards8** [comment]
The current .editorconfig is fine and it has been something we've needed to do for a while. 

Sounds good.

**Pull request closed without merging**
