### PR TITLE
Added option to change the smiley face

### PR DESCRIPTION
**Pull request by uttarayan21**
rewrote a function in battery.sh to make use of acpi command in linux if it exists or else fallback to /sys/class/power_supply/BAT*
added option to switch powerline separators
added option to switch the smiley face with window name or any other character issue #14

### CODE REVIEW

**Comment by uttarayan21** [comment]
Screenshot from 2020-05-21 21-40-17

Here is a screenshot of how it looks now

**Comment by ethancedwards8** [comment]
Dang, I was going to do this today, beat me to it :+1: :smile:

**Comment by ethancedwards8** [comment]
Also, you might want to make an entry in INSTALL.md

**Comment by danerwilliams** [comment]
Some users have reported issues with the change in battery.sh from #22 so it was reverted in back to the original battery script with #26 . 

Can you resolve merge conflicts and use the fall back option to what was merged in #26 ? 

Also, can you explain the advantage of using acpi command if it exists?

**Comment by uttarayan21** [comment]
Oh sorry about the #22 commit it didn't test it extensively.
And about the acpi command, it works well for me while the /sys/class/power_supply/BAT0 usually changes in between reboots and I have to change some of my scripts.
Also right now I'm stuck in a power outage due to a cyclone amphan and won't be able to change the commits maybe for a few days.

**Comment by uttarayan21** [comment]
Hi I fixed the merge conflicts and added entries to INSTALL.md

**Comment by danerwilliams** [comment]
The changes to dracula.sh are great. 

My only concern is with the changes to battery.sh. In #26 the battery was fixed by reverting back to it's original state, and it looks like for the fall back if acpi isn't present that the fallback is what battery.sh looked like before it was fixed in #26 . Can you please change it accordingly?

**Comment by uttarayan21** [comment]
Yes the changes before #26 were bugged but now its a llittle different
before #26 I tried to list all the folders in /sys/class/power_supply/ starting with BAT
but that led to ls listing all files inside BAT0 or BAT1 so I've done this
ls -d /sys/class/power_supply/BAT* 
which only lists directories in /sys/class/power_supply that start with BAT
I hope this addressed your concerns.

**Pull request merged**
