### PR TITLE
Add tmux-continuum status plugin

### PR DESCRIPTION
**Pull request by aaronkollasch**
This PR shows the status of the latest [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum) save and a countdown to the next save.

If no save is present:
Screenshot 2023-06-17 at 5 09 58 PM
When a save occurs:
Screenshot 2023-06-17 at 5 24 57 PM
Then the timer resets:
Screenshot 2023-06-17 at 5 25 11 PM

### CODE REVIEW

**Comment by xiantang** [comment]
well done

**Comment by ethancedwards8** [comment]
Code looks good. I'm just not sure if this is feature creep or not. Can you justify this instead of putting it in a [script](https://github.com/dracula/tmux/commit/e8598158df58415e9413dddd34c9f818335443d0)?

**Comment by aaronkollasch** [comment]
It's up to you. I did a brief survey of tmux plugins and [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum) has 2.7k stars, more than [tmux-yank](https://github.com/tmux-plugins/tmux-yank), about 1/4 of [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect) or the plugin manager [tpm](https://github.com/tmux-plugins/tpm), and about 1/10 of [tmux](https://github.com/tmux/tmux) itself. So I'd say tmux-continuum seems like a popular plugin. Also, if it's a separate script I'm not sure how people would find it.

**Comment by ethancedwards8** [comment]
That's fair, thanks for the contribution!

**Comment by aaronkollasch** [comment]
Thanks for reviewing!

**Pull request merged**
