### PR TITLE
mac: Fix network detection

### PR DESCRIPTION
**Pull request by fvincenzo**
There air wifi networks that are not compatible with AirPort. In such a case the network.sh script does not detect correctly the SSID.

The message reported is:
  "You are not associated with an AirPort network."

Fix the script detecting correctly the SSID of networks that do not support AirPort.

### CODE REVIEW

**Comment by ethancedwards8** [comment]
We actually have an existing PR https://github.com/dracula/tmux/pull/291 . Thank you thought.

**Comment by fvincenzo** [comment]
Not a problem, happy to help. According to me PR #291 has a couple of problems in it's last iteration:
- Invokes ipconfig twice.
- If the network has airport support `networksetup` should be the preferred way to detect the SSID.
Where should I put these comments?

**Comment by ethancedwards8** [comment]
> @ethancedwards8 Not a problem, happy to help. According to me PR #291 has a couple of problems in it's last iteration:
> 
>     * Invokes ipconfig twice.

That's a good point.
> 
>     * If the network has airport support `networksetup` should be the preferred way to detect the SSID.
>       Where should I put these comments?

I'm not sure I understand. Why is that preferable?

**Comment by fvincenzo** [comment]
> I'm not sure I understand. Why is that preferable?
So that we have a fallback mechanism in place, if `networksetup` fails we fallback on ipconfig.

**Comment by ethancedwards8** [comment]
Thank you for your contribution.

**Pull request merged**
