### PR TITLE
Adding ability to change the refresh rate of whole status bar

### PR DESCRIPTION
**Pull request by ethancedwards8**
I'll take another crack at this tomorrow, this idea just popped in my head and thought I would share, thoughts?

### CODE REVIEW

**Comment by ethancedwards8** [comment]
Figured it out, the reasoning is because a faster refresh rate may product more up to date information, but a slower refresh rate would be more battery efficient

**Comment by ethancedwards8** [comment]
#59

**Comment by ethancedwards8** [comment]
#61

**Comment by ethancedwards8** [comment]
Do we have an ETA of when my PR or the others will get merged?

**Comment by danerwilliams** [comment]
Sorry, I've been super busy with classes and haven't had much of a chance to look at things here. I will probably try and work on them some time next week. 

On a related note, I think it could be worth adding another maintainer to the project to help load balance when I am unavailable to check in on things. @ethancedwards8 you've been pretty involved, would you be interested?

**Comment by ethancedwards8** [comment]
All good. 

Sure, I’d love to! My classes have also started but only 2 days a week, so I would have plenty of time to help out.

**Pull request merged**
