### PR TITLE
Added padding at the end of left icon for custom args

### PR DESCRIPTION
**Pull request by Memije**
When using the `dracula-show-left-icon` option with a custom character, there's missing padding to the right of the character like so

Screen Shot 2020-11-20 at 18 06 48

To fix this, the extra padding was added when assigning the `left_icon` variable

### CODE REVIEW

**Comment by ethancedwards8** [comment]
Yeah hm, I find this kinda odd, in some terminal emulators the spacing isn't needed, but on some they are. Like I'm on Linux and using the Kitty terminal emulator and there is already a pretty big gap.

**Comment by ethancedwards8** [comment]
Maybe we could make this an option? Because this is definitely annoying.

**Comment by danerwilliams** [comment]
> Maybe we could make this an option? Because this is definitely annoying.

I second this

**Comment by ethancedwards8** [comment]
Bumping, progress report? @Memije

**Comment by Memije** [comment]
> Bumping, progress report? @Memije

@ethancedwards8 updated

**Comment by ethancedwards8** [comment]
Nice, thanks!

**Pull request merged**
