### PR TITLE
Added kubernetes-context plugin

### PR DESCRIPTION
**Pull request by JannoTjarks**
This pull request is adding a plugin for kubernetes. It shows the current kubernetes status in the statusbar. It needs the tool kubectl installed. 

image

With the variable dracula-kubernetes-context-label the user can add a prefix for the statusbar entry.
image

### CODE REVIEW

**Comment by pentago** [comment]
Any chance we can get this one today? :wink wink:

**Comment by JannoTjarks** [comment]
Hi @ethancedwards8  , what is the current status?

**Comment by ethancedwards8** [comment]
I'm hesitant to merge this because of the use of an external tool. I realize the Git module used an external tool, but it's more mainstream and widespread.

**Comment by JannoTjarks** [comment]
Hi @ethancedwards8, i understand your hesitate. But all users working with kubernetes got kubectl installed. 

As @pentago shows, there is a wish/need for a plugin like this. 
There are also existing solution like https://github.com/jonmosco/kube-tmux which will not work which dracula/tmux. The users understand, that the need kubectl as binary installed. It should be enough, to communicate it to the users through the README.

**Comment by pentago** [comment]
Correct. If someone works with Kubernetes they abaolutely have kubectl installed, without it they can't interface with the API server so having kubectl is a must.

**Pull request merged**
