### PR TITLE
Adding GPU usage.

### PR DESCRIPTION
**Pull request by ethancedwards8**
#45 @backpropper

### CODE REVIEW

**Comment by ethancedwards8** [comment]
I have an nvidia on my system, so I don't have any way to test an AMD gpu, also I don't have access to a Mac with a GPU so I'm stuck there. This is just getting the ball rolling.

**Comment by danerwilliams** [comment]
Is there no way to monitor gpu's in general?

**Comment by danerwilliams** [comment]
It looks like we can see how they calculate it in this [tmux-gpu plugin](https://github.com/tmux-plugins/tmux-cpu). Appears they only have nvidia compatibility as well.

**Comment by ethancedwards8** [comment]
I'm not aware of a way to monitor GPU's in general.

**Comment by danerwilliams** [comment]
I don't have a nvidia gpu to test myself on, but since it can be disabled and it seems like this is consistent with other implementations of the gpu usage percent, I am going to trust your tests and merge it.

**Comment by backpropper** [comment]
Thanks for adding this @ethancedwards8. I haven't seen any API for checking gpu usage for AMD/Intel GPUs so might as well ignore for now.

**Comment by backpropper** [comment]
It seems like now the status bar does not show any of the CPU/GPU percentage? Did anything change?

**Pull request merged**
