### PR TITLE
Adding military time functionality

### PR DESCRIPTION
**Pull request by ethancedwards8**
I think I've did this correct, if I haven't please let me know and I'll be happy to fix this

The way it works is you can set `set -g @dracula-tmux-miiltary true` and it'll set the time in the bottom to military time instead of a 12 hour time. This is my first PR so if I did anything wrong my bad.

### CODE REVIEW

**Comment by danerwilliams** [comment]
I tried testing it and it didn't seem to work. It also looks like you deleted the parameter for showing powerline by accident. Can you make changes to fix and then test to see if it works on your end then push changes? Otherwise idk why it's not working on my end.

**Comment by ethancedwards8** [comment]
The reason I'm missing the powerline stuff is that all of this is from a outdated branch, I originally cloned the repo like a few weeks ago, because I had that idea then, but I just had the time to do it now, I'll try and fix whatever happened though. If you could give me some guidance on how to get it back up to date that'd be great.

**Comment by danerwilliams** [comment]
oh ok that makes sense. It's not very difficult for me to resolve those merge conflicts so don't worry about that. When I resolved them on my local though military time didn't work when I set my configuration. Is this consistent with what's happening on your end?

**Comment by ethancedwards8** [comment]
I actually just figured it out and its synced now lol. But yes, oddly enough it was working earlier, let me see if I accidently deleted any code, or if there's something I've overlooked. Do you notice any immediate errors in the code?

**Comment by danerwilliams** [comment]
Honestly everything made sense to me so I was a bit confused why It wasn't working lol, I'll try again in a bit, may have just been something weird on my end.

**Comment by ethancedwards8** [comment]
Well oddly enough it isn't working for me now, I did regenerate my local (I'm running Linux) earlier today, maybe that's causing it, should I make a new file dedicated to that function like how the other ones are?

**Comment by danerwilliams** [comment]
I'm not sure what you mean by that, what are the other one's you're referencing?

**Comment by ethancedwards8** [comment]
Like if I want to disable the Fahrenheit converter on the weather script, if you go into `dracula.sh` and go down to the `if $show_weather; then` it runs a script from another file, I'm saying do you think separating the script into a different file would fix the issue?

**Comment by danerwilliams** [comment]
Oh no that is definitely not necessary, it was originally set by just just that one line of code that you put if statements around.

I may be totally off on this, but I think I remember that 24 hour was the default when I originally made this project and I had to change it to 12 hour by adding that line. Maybe try researching a little bit more or seeing what happens when you just get rid of that part and have nothing there? ie eliminate the 12 and 24 hours things you made and see what happens, if it does in fact default to 24 then just add an if statement so that if show_military is false then change to 12 hour.

**Comment by ethancedwards8** [comment]
Oh hmm, that may totally be a possibility, let me try that, I have a feeling you may be correct in that.

**Comment by danerwilliams** [comment]
Also, once you have it working please add to INSTALL.md under the configuration section.

**Comment by ethancedwards8** [comment]
So this may be a stupid question but, I can't seem to get tmux to reload correctly, I'm doing `tmux source ~/.tmux.conf` and then doing `prefix + I` but nothing is changing, am I doing this right? Also yes, I can add to that, I was going to do that originally in my PR but I forgot to.

**Comment by danerwilliams** [comment]
I've found that method isn't very effective for testing out code on tmux, it usually isn't responsive for me either. It also requires that you have changes committed and pushed which is not ideal. 

I would just run the dracula.tmux executable in whatever local repo you are editing on: `./dracula.tmux`

**Comment by ethancedwards8** [comment]
Ohhh okay thank you, that makes sense.

**Comment by ethancedwards8** [comment]
I think I may have figured the issue out, tmux uses a time system called strftime, and in some of the code, its setting it to use standard 12 hour time, I think I know a way to fix this, but I'll have to work on it tomorrow, it's getting quite late where I am. Thanks for all the help tonight, I'll try and get you a working commit tomorrow.

**Comment by ethancedwards8** [comment]
Everything should be working! Working perfectly on my end, learned a bit more about git today, my suspicion last night was correct.

**Pull request merged**
